#Q1.Read the file named “prices.csv” 

In [1]:
# To enable plotting graphs in Jupyter notebook
%matplotlib inline
# Numerical libraries
import numpy as np
# to handle data in form of rows and columns
import pandas as pd 
# importing plotting libraries
import matplotlib.pyplot as plt 
#importing seaborn for statistical plots
import seaborn as sns
prj6_df_org = pd.read_csv("\Project\\prices.csv")
prj6_df = prj6_df_org
prj6_df.head()

date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   
2  2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000  119.739998   
3  2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000  117.440002   
4  2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996  117.330002   

      volume  
0  2163600.0  
1  2386400.0  
2  2489500.0  
3  2006300.0  
4  1408600.0

In [2]:
prj6_df.shape,prj6_df.size

((851264, 7), 5958848)

In [3]:
prj6_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


In [4]:
prj6_df.describe().T

count          mean           std   min           25%  \
open    851264.0  7.083699e+01  8.369588e+01  0.85  3.384000e+01   
close   851264.0  7.085711e+01  8.368969e+01  0.86  3.385000e+01   
low     851264.0  7.011841e+01  8.287729e+01  0.83  3.348000e+01   
high    851264.0  7.154348e+01  8.446550e+01  0.88  3.419000e+01   
volume  851264.0  5.415113e+06  1.249468e+07  0.00  1.221500e+06   

                 50%           75%           max  
open    5.277000e+01  7.988000e+01  1.584440e+03  
close   5.280000e+01  7.989000e+01  1.578130e+03  
low     5.223000e+01  7.911000e+01  1.549940e+03  
high    5.331000e+01  8.061000e+01  1.600930e+03  
volume  2.476250e+06  5.222500e+06  8.596434e+08

In [5]:
cat_col = []  # list to hold the categorical features
for i in prj6_df.columns:  # Loop to go through each and every column name
    if prj6_df[i].dtype == object:  # check if the column is of object type
        cat_col.append(i)  # append the ones that satisfy above condition to the list
    prj6_df.loc[0:3, cat_col]
for i in cat_col:
    print(f'Number of categories in {i} = {len(prj6_df[i].unique())}')

Number of categories in date = 3524
Number of categories in symbol = 501


#Q2.Drop all the rows with null values.

#There are no null values in the data to drop.

#Q3.Drop columns: “date”, “volume” and “symbol” 

In [6]:
prj6_df = prj6_df.drop(columns= ['date','volume','symbol'])
prj6_df.head()

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002

#Q4.Get “close” as the target column and rest of the columns as features 

In [7]:
features = prj6_df.drop(columns= ['close'])
target = prj6_df.close

In [8]:
features.shape,target.shape

((851264, 3), (851264,))

#Q5.Split the data into training and testing 

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.3, random_state = 10)

In [10]:
(X_train.shape),(X_test.shape),(y_train.shape),(y_test.shape)

((595884, 3), (255380, 3), (595884,), (255380,))

#Q6.Scale the data (features only) 

In [11]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
y_test = sc.transform(X_test)

#Q7.Convert features and labels to numpy array 

In [12]:
import numpy as np
X = np.array(X_train)
y = np.array(y_train)
X.shape,y.shape

((595884, 3), (595884,))

In [13]:
X

array([[-0.18066333, -0.17499134, -0.18062612],
       [ 1.07367034,  1.05975655,  1.05661349],
       [ 0.93261591,  0.94551272,  0.94321271],
       ...,
       [ 0.07817502,  0.08097235,  0.07656551],
       [ 0.20836981,  0.21244906,  0.20013579],
       [-0.19438687, -0.19644215, -0.19635322]])

In [14]:
y

array([ 55.950001, 159.929993, 148.630005, ...,  77.790001,  88.43    ,
        53.889999])

#Q8.Reshape the features to make it suitable for input in the model 

#No Reshape required for this data

#Q9.Define the sequential model 

In [15]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model

#Add a flatten layer

In [16]:
model.add(tensorflow.keras.layers.Flatten())
model

#Add Dense layer with linear activation function and one neuron

In [17]:
model = Sequential()
model.add(Dense(32, activation = 'relu', input_dim = 3))
model.add(Dense(1,))
model

#Q10. Compile the model 

In [18]:
model.compile(loss='mean_squared_error')
model

#Q10.1 Use loss as “mean squared error”

In [19]:
model.compile(loss='mean_squared_error')
model

#Q10.2 Use optimizer as “sgd”

In [20]:
model.compile(optimizer='sgd', loss='mean_squared_error', metrics = ['accuracy'])
model

#Q11.Print summary of the model 

In [21]:
model.fit(X, y, batch_size = 10, epochs = 3)
model.summary()

Train on 595884 samples
Epoch 1/3
595884/595884 [==============================] - 121s 203us/sample - loss: nan - accuracy: 0.0000e+00
Epoch 2/3
595884/595884 [==============================] - 118s 198us/sample - loss: nan - accuracy: 0.0000e+00
Epoch 3/3
595884/595884 [==============================] - 118s 199us/sample - loss: nan - accuracy: 0.0000e+00
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                128       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 161
Trainable params: 161
Non-trainable params: 0
_________________________________________________________________


#Q12.Fit the model 

In [22]:
# Initialising the NN
model = Sequential()

# Adding the input layer and the first hidden layer
model.add(Dense(32, activation = 'relu', input_dim = 3))

# Adding the second hidden layer
model.add(Dense(32, activation = 'relu'))

# Adding the third hidden layer
model.add(Dense(32, activation = 'relu'))

# Adding the output layer

model.add(Dense(1))

# Compiling the NN
model.compile(optimizer = 'adam', loss = 'mean_squared_error',metrics = ['accuracy'])

# Fitting the ANN to the Training set
model.fit(X, y, batch_size = 10, epochs = 5)

Train on 595884 samples
Epoch 1/5
595884/595884 [==============================] - 149s 249us/sample - loss: 40.4997 - accuracy: 5.0345e-06
Epoch 2/5
595884/595884 [==============================] - 145s 243us/sample - loss: 2.9362 - accuracy: 5.0345e-06
Epoch 3/5
595884/595884 [==============================] - 144s 241us/sample - loss: 2.3648 - accuracy: 5.0345e-06
Epoch 4/5
595884/595884 [==============================] - 151s 254us/sample - loss: 1.9960 - accuracy: 5.0345e-06
Epoch 5/5
595884/595884 [==============================] - 161s 269us/sample - loss: 1.9990 - accuracy: 5.0345e-06


#Q12.1 Use 50 epochs

In [23]:
model.fit(X, y, batch_size = 100, epochs = 50)

Train on 595884 samples
Epoch 1/50
595884/595884 [==============================] - 17s 28us/sample - loss: 0.6951 - accuracy: 5.0345e-06
Epoch 2/50
595884/595884 [==============================] - 15s 25us/sample - loss: 0.7679 - accuracy: 5.0345e-06
Epoch 3/50
595884/595884 [==============================] - 15s 24us/sample - loss: 0.7140 - accuracy: 5.0345e-06
Epoch 4/50
595884/595884 [==============================] - 16s 27us/sample - loss: 0.7042 - accuracy: 5.0345e-06
Epoch 5/50
595884/595884 [==============================] - 18s 30us/sample - loss: 0.7026 - accuracy: 5.0345e-06
Epoch 6/50
595884/595884 [==============================] - 17s 28us/sample - loss: 0.6545 - accuracy: 5.0345e-06
Epoch 7/50
595884/595884 [==============================] - 17s 28us/sample - loss: 0.6543 - accuracy: 5.0345e-06
Epoch 8/50
595884/595884 [==============================] - 17s 29us/sample - loss: 0.6398 - accuracy: 5.0345e-06
Epoch 9/50
595884/595884 [==============================] - 17s 

#Q12.2 Use batch size as 128 for fast training

In [24]:
model.fit(X, y, batch_size = 128, epochs = 5)

Train on 595884 samples
Epoch 1/5
595884/595884 [==============================] - 13s 21us/sample - loss: 0.5529 - accuracy: 5.0345e-06
Epoch 2/5
595884/595884 [==============================] - 12s 20us/sample - loss: 0.5519 - accuracy: 5.0345e-06
Epoch 3/5
595884/595884 [==============================] - 11s 19us/sample - loss: 0.5654 - accuracy: 5.0345e-06
Epoch 4/5
595884/595884 [==============================] - 12s 20us/sample - loss: 0.5518 - accuracy: 5.0345e-06
Epoch 5/5
595884/595884 [==============================] - 11s 19us/sample - loss: 0.5441 - accuracy: 5.0345e-06


#Q13.Do predictions on test data and evaluate the result 

In [25]:
y_pred = model.predict(X_test)
print(y_pred)

[[7560.747 ]
 [2926.0276]
 [2844.796 ]
 ...
 [6831.443 ]
 [3089.0884]
 [4547.8525]]


#Q14.Do some custom predictions on your own manual inputs.

In [26]:
ManualTest_df=pd.read_csv("Project\\Test.csv")
sc=StandardScaler()
M_Test = sc.fit_transform(ManualTest_df)
manual_pred = model.predict(M_Test)
print(manual_pred)

[[  0.37561214]
 [154.54877   ]]
